export const avators = [
  {
    name: "百田夏菜子",
    shortName: "百田夏菜子",
    src: "/kanakomomota_official.jpg",
    key: "momotakanako",
    link: "kanakomomota_official",
  },
  {
    name: "玉井詩織",
    shortName: "玉井詩織",
    src: "/shioritamai_official.jpg",
    key: "tamaishiori",
    link: "shioritamai_official",
  },
  {
    name: "佐々木彩夏",
    shortName: "佐々木彩夏",
    src: "/ayaka_sasaki_official.jpg",
    key: "sasakiayaka",
    link: "ayaka_sasaki_official",
  },
  {
    name: "高城れに",
    shortName: "高城れに",
    src: "/takagireni_official.jpg",
    key: "takagireni",
    link: "takagireni_official",
  },
  {
    name: "Momoiro Clover Z Channel",
    shortName: "公式YouTube",
    src: "/momoriocloverzchannel.jpg",
    key: "Momoiro Clover Z Channel",
    link: "kanakomomota_official",
  },
  {
    name: "ももクロインフォ公式",
    shortName: "インフォ",
    src: "/information_mcz.jpg",
    key: "information_mcz",
    link: "information_mcz",
  },

  {
    name: "『ももクロChan』",
    shortName: "Chan",
    src: "/momoclochan_ex.jpg",
    key: "momoclochan_ex",
    link: "momoclochan_ex",
  },
  {
    name: "『ももクロちゃんと！』【テレビ朝日公式】",
    shortName: "ちゃんと！",
    src: "/momoclochanto.jpg",
    key: "momoclochanto",
    link: "momoclochanto",
  },
  {
    name: "川上アキラの人のふんどしでひとりふんどし",
    shortName: "ふんどし",
    src: "/hitorifundoshi.jpg",
    key: "hitorifundoshi",
    link: "hitorifundoshi",
  },
  {
    name: "高城れにの週末ももクロ☆パンチ！！",
    shortName: "ももパン",
    src: "/momoclo_punch.jpg",
    key: "momoclo_punch",
    link: "momoclo_punch",
  },
  {
    name: "ももくろちゃんZ",
    shortName: "ちゃんZ",
    src: "/momoclo_chanz.jpg",
    key: "momoclo_chanz",
    link: "momoclo_chanz",
  },
  {
    name: "momoiroclover",
    shortName: "川上あきら",
    src: "/momoiroclover.jpg",
    key: "momowgp",
    link: "momowgp",
  },
];
